name: Develop

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'

jobs:

  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle-wrapper.properties') }}
      - uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Detekt
        run: ./gradlew detekt
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Detekt
          path: "build/reports/detekt/detekt.html"
          if-no-files-found: error
      - name: Lint Debug
        run: ./gradlew lintDebug
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Lint
          path: "*/build/reports/lint-results*.html"
          if-no-files-found: error

  build:
    needs: [analysis]
    runs-on: ubuntu-latest
    env:
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle-wrapper.properties') }}
      - uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Assemble Debug
        run: ./gradlew assembleDebug
      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Assemble
          path: "app/build/outputs/apk/debug/*.apk"
          if-no-files-found: error
      - name: Bundle Debug
        run: ./gradlew bundleDebug
      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Bundle
          path: "app/build/outputs/bundle/debug/*.aab"
          if-no-files-found: error
